In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
fastball_speed = np.random.randint(90,106,size=500)

In [5]:
tommy_john = np.where(fastball_speed>96,np.random.choice([0,1],size=500, p= [0.3,0.7]),0)

In [6]:
d = {'fastball_speed': fastball_speed,'tommy_john': tommy_john}

In [7]:
df = pd.DataFrame(data=d)

In [8]:
df

fastball_speed  tommy_john
0                96           0
1                93           0
2               102           1
3               104           1
4               100           0
..              ...         ...
495             104           1
496              92           0
497             101           1
498              90           0
499              93           0

[500 rows x 2 columns]

In [9]:
X = df[['fastball_speed']]

In [10]:
y = df[['tommy_john']]

In [11]:
#normal train tes split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test, y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
lr = LogisticRegression()

In [16]:
lr.fit(X_train,y_train.values.ravel())

LogisticRegression()

In [17]:
lr.score(X_test,y_test)

0.81

In [18]:
#test this again

In [19]:
X2_train,X2_test, y2_train,y2_test = train_test_split(X,y,random_state=25,test_size=0.2)

In [20]:
lr.fit(X2_train,y2_train.values.ravel())

LogisticRegression()

In [21]:
lr.score(X2_test,y2_test)

0.8

In [22]:
# basic cross validation

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cvscore = cross_val_score(lr,X,y.values.ravel(),cv=10)

In [25]:
cvscore

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [26]:
np.average(cvscore)

np.float64(0.756)

In [27]:
np.std(cvscore)

np.float64(0.04270831300812523)

In [28]:
# define standard kfold

In [29]:
from sklearn.model_selection import KFold

In [30]:
kf = KFold(n_splits=15,shuffle=True,random_state=42)

In [31]:
kfscore = cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='f1')

In [32]:
kfscore2 = cross_val_score(lr,X,y.values.ravel(),cv=kf,scoring='accuracy')

In [33]:
kfscore

array([0.66666667, 0.82758621, 0.72727273, 0.7027027 , 0.6875    ,
       0.72727273, 0.74074074, 0.72      , 0.66666667, 0.60869565,
       0.66666667, 0.63157895, 0.64516129, 0.66666667, 0.6       ])

In [34]:
np.average(kfscore)

np.float64(0.6856785107611354)

In [35]:
np.std(kfscore)

np.float64(0.05620337068328653)

In [36]:
kfscore2

array([0.76470588, 0.85294118, 0.82352941, 0.67647059, 0.70588235,
       0.81818182, 0.78787879, 0.78787879, 0.78787879, 0.72727273,
       0.72727273, 0.78787879, 0.66666667, 0.78787879, 0.63636364])

In [37]:
np.average(kfscore2)

np.float64(0.7559120617944146)

In [38]:
np.std(kfscore2)

np.float64(0.060970963505883366)

In [39]:
#stratified K Fold

In [40]:
from sklearn.model_selection import StratifiedKFold

In [41]:
kf3 = StratifiedKFold(n_splits=10,shuffle=True,random_state=11)

In [42]:
kfscore3 = cross_val_score(lr,X,y.values.ravel(),cv=kf3)

In [43]:
kfscore3

array([0.66, 0.76, 0.76, 0.8 , 0.8 , 0.74, 0.76, 0.74, 0.78, 0.76])

In [44]:
np.average(kfscore3)

np.float64(0.756)

In [45]:
np.std(kfscore3)

np.float64(0.03773592452822642)

In [46]:
# pipeline example!

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()

In [49]:
from sklearn.pipeline import make_pipeline

In [50]:
pipe1 = make_pipeline(scaler,lr)

In [51]:
pipe1.fit(X_train,y_train.values.ravel())

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [52]:
scorespipe = cross_val_score(pipe1,X,y.values.ravel(),cv=10)

In [53]:
scorespipe

array([0.68, 0.78, 0.72, 0.72, 0.78, 0.82, 0.74, 0.74, 0.76, 0.82])

In [54]:
np.average(scorespipe)

np.float64(0.756)

In [55]:
np.std(scorespipe)

np.float64(0.04270831300812523)