# Scipy Graphs

In [30]:
# working with graphs: we have a module named scipy.sparse.csgraph
# adjacency Matrix: nxn matrix,where n is the number of elements in the graph.
# Connected Component:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

mtx=np.array([[0,1,2],[1,0,0],[2,0,0]])
mtxnew=csr_matrix(mtx)
print(connected_components(mtxnew))

(1, array([0, 0, 0], dtype=int32))


In [31]:
# Dijkstra method:For finding shortest path in a graph form one element to another
# it take 3 arg: return_predecessors,indices,limit
# here we will find to shrtest path from element 1 to 2:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

mtx=np.array([[0,1,2],[1,0,0],[2,0,0]])
mtxnew=csr_matrix(mtx)
print(dijkstra(mtxnew,return_predecessors=True,indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0], dtype=int32))


In [32]:
# Floyd Worshall() method: it is for finding the shortest path between all pairs of elements.
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

mtx=np.array([[0,1,2],[1,0,0],[2,0,0]])
mtxnew=csr_matrix(mtx)
print(floyd_warshall(mtxnew,return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [33]:
# Bellman_ford() method: it is for finding the shortest path between all pairs of elements but this method can handle negative weights as well.
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

mtx=np.array([[0,-1,2],[1,0,0],[2,0,0]])
mtxnew=csr_matrix(mtx)
print(bellman_ford(mtxnew,return_predecessors=True))

(array([[ 0., -1.,  2.],
       [ 1.,  0.,  3.],
       [ 2.,  1.,  0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]], dtype=int32))


In [34]:
# Depth first order: it returns a depth first traversal froma node: it has 2 arguments:the graph, starting element
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

mtx=np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
mtxnew=csr_matrix(mtx)
print(depth_first_order(mtxnew,1))

(array([1, 0, 3, 2], dtype=int32), array([    1, -9999,     1,     0], dtype=int32))


In [35]:
# breadth first order() method: it returns the breadth from a node: it has 2 arguments:the graph, starting element
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

mtx=np.array([[0,1,0,1],[1,1,1,1],[2,1,1,0],[0,1,0,1]])
mtxnew=csr_matrix(mtx)
print(breadth_first_order(mtxnew,1))

(array([1, 0, 2, 3], dtype=int32), array([    1, -9999,     1,     1], dtype=int32))
